escher/src/text_area.cpp
liba/Makefile

Those two warnings showed up while building the whole thing, it wasn't very beautiful in the terminal :)
* `escher/src/text_area.cpp:113:25`: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
* `liba/src/external/openbsd/k_rem_pio2f.c:66:54`: warning: this 'for' clause does not guard this statement, but the latter is misleadingly indented as if it is guarded by the 'for' [-Wmisleading-indentation]

build: fix warnings

---

poincare/include/poincare/symbol.h
poincare/src/symbol.cpp

This generated a lot of warnings in -Wextra: `'const' type qualifier on return type has no effect [-Wignored-qualifiers]`

[poincare] remove useless const qualifier on return type

---

ion/src/simulator/keyboard/fltkkbd.cpp

This makes the simulator platform _much_ easier to use on a keyboard with a proper keypad. It is specifically tailored for the `Calculation` app, but it should be fine elsewhere.

[ion/simulator] Improve key mapping

---

apps/Makefile
apps/apps_window.cpp
apps/i18n.cpp
apps/i18n.h
apps/shift_alpha_lock_view.cpp
apps/shift_alpha_lock_view.h
apps/title_bar_view.cpp
apps/title_bar_view.h

This adds the text 'shift' when the shift key is activated. No functionality changes were made.

Add shift activated text (Fix #22)

---

apps/sequence/graph/term_sum_controller.cpp
apps/settings/main_controller.cpp
apps/settings/sub_controller.cpp
poincare/src/symbol.cpp

Following a comment of mine [here](https://github.com/numworks/epsilon/pull/65/files#r136870515)...
* Another buffer overflow was happening when changing the complex format in the settings (instant crash with ASan)
* All const char arrays manually ending with a nul char were trimmed of it considering StringLayout allocs one already.
* Use automatic compile-time array-size when possible, it avoids mistakes.
I was tempted to make a macro like `#define AutoStringLayout(charArray) new StringLayout(charArray, sizeof(charArray))` but oh well :)

[various apps] StringLayout: fix buffer overflow and use auto size

---

build/platform.device.mak

We now display a small inline tutorial, and wait for a device to be
connected.
Fix #83

Improve the app_flash command

---

apps/calculation/text_field.cpp

My girlfriend was using the calculator and was becoming confused when it kept entering `ans-` when she pressed`-`. She was trying to do basic calculations with negative numbers and was getting held up.
Perhaps in future this could be a modal feature but for now I suggest removing the addition of `ans` when `-` is the first character pressed.

Removed the automatic insertion of 'ans' when pressing '-'.

---

build/platform.device.mak

The recipe for the 'app_flash' target uses an 'until' loop to wait for
the DFU device to be connected.  The command uses &> to redirect both
standard output and standard error output to a file (/dev/null).  This
works for shells such as Bash and Z Shell, but not dash or Korn shell.
Replace it with a combination of > and 2>&1 for portability.

Makefile: Use POSIX shell redirection syntax for app_flash target

---

poincare/src/store.cpp

When m_value was passed to setExpressionForSymbolName directly, and the m_symbol existed in the global context, it ended up evaluating the expression relative to the global context instead of the current context.

Fix #108 and #109 storing expressions containing variables

---

liba/include/stdint.h

[liba] Optimize int_fast_t typedefs for arm.

---

poincare/src/integral.cpp

The recursive adaptiveQuadrature() function is initially called with the
maximum number of recursion levels to perform, so adaptiveQuadrature()
should decrement numberOfRecursions at each recursion level.
When adaptiveQuadrature() needs to recurse, it splits the interval in
two, calculates the integral for each half by calling itself
recursively, and adds the result from each half.  However, it then
ignores this result and returns NAN because it is checking a stale
quadKG.absoluteError value.  Rearrange the code to avoid that.

[Fix #130] [poincare] Fix recursion bug in adaptiveQuadrature() integration

---

apps/graph/app.cpp
apps/graph/app.h
apps/shared/text_field_delegate_app.cpp
apps/shared/text_field_delegate_app.h

Inside the first argument of `diff` or `int`, `x,n,t` should type `x`.
Inside the first argument of `product` or `sum`, `x,n,t` should type `n`.
Otherwise, fallback to `x` in the graph app, `n` in the sequence app, and `X` elsewhere since `x` would be useless.

Improve the [x,n,t] key.

---

apps/shift_alpha_lock_view.cpp

ARM GCC 6.3 was complaining about it, for some reason.

shift alpha lock view: fix gcc warning about a missing return in numberOfSubviews

---

python/port/port.c

The n_args parameter of mp_builtin_open() has type size_t in
"python/src/py/builtin.h", and type uint in "python/port/port.c".
Change it to size_t.

[python] Fix type of n_args parameter of mp_builtin_open()

---

poincare/src/fraction.cpp
poincare/test/fraction.cpp

This can be observed by computing 1E155/1E155(1+i) which returns inf even though this is equivalent to 1/(1+i) == (1-i)/2 == .5-.5i

Fix potential overflow in complex division calculation.

---

.travis.yml

We should be able to use a container-based Travis environment.
Faster boot times, no dependency on developer.arm.com being online.

Use container-based Travis environment

---

apps/settings/language_controller.cpp

The condition check is done last since the event could be handled by the deeper implementation (shared language controller) already.

[settings] allow left event to pop out of the lang controller (fix #180)

---

apps/settings/main_controller.cpp
poincare/src/matrix.cpp

Those are quite minor, so the fixes are trivial, but other (more important) issues exist (for instance [that one](https://scan4.coverity.com/reports.htm#v15949/p12091/fileInstanceId=28662377&defectInstanceId=5676388&mergedDefectId=200502), buffer overflow) but I haven't really looked into them yet.
There was a false-positive, too, involving an out-of-bounds access regarding w_n, but that's fine for now since it's not in use yet (and when it will be, the vector will be correctly sized).

A few misc. coverity fixes

---

ion/src/simulator/init.cpp
ion/src/simulator/keyboard/fltkkbd.cpp

Hi all,
A solution to fix #240, is to set font "Arial Unicode MS" for Windows platform. It's because, default Windows Arial is not fully unicode...
ion/src/simulator/init.cpp
Fl::set_font(FL_SYMBOL, "Arial Unicode MS");
ion/src/simulator/keyboard/fltkkbd.cpp
m_buttons[k]->labelfont(FL_SYMBOL);

Fix: invalid characters on windows simulator #240

---

ion/src/device/device.cpp
ion/src/device/regs/flash.h

Enabling instruction and data cache speed up the calculator a little bit.
For example, the mandelbrot set in the python application takes 1 minutes 30 seconds to render with this modification, and about 2 minutes without.
This should not raise power consumption  as stated [here](http://www.st.com/content/ccc/resource/technical/document/application_note/13/0a/06/b9/1e/2f/4d/9d/DM00096220.pdf/files/DM00096220.pdf/jcr:content/translations/en.DM00096220.pdf) (but not clearly) or [here](http://www.st.com/content/ccc/resource/technical/document/application_note/77/74/4f/da/9b/9c/43/e7/DM00033348.pdf/files/DM00033348.pdf/jcr:content/translations/en.DM00033348.pdf) (for the F2 family) in the section ART accelerator.
Instruction prefetch may be also enabled, but this can make the power consumption …

Enable instruction and data cache

---

apps/global_preferences.cpp

Global pref isn't init when the init of MathToolbox:
static GlobalPreferences s_globalPreferences doesn't init on windows platform, move to
static methode sharedGlobalPreferences()

Fix: windows simulator: Assert error apps/i18n.cpp:2437 and Toolbox title "Zoom :" #267

---

ion/src/emscripten/events_keyboard.cpp

This allows typing &#x1D07;, &pi;, imaginary i, and newline from the keyboard on the online simulator.

More keyboard shortcuts for the emscripten platform.

---

poincare/src/expression_lexer.l

If no other rule matches before, lex yields an UNDEFINED_SYMBOL. This
seems more future-proof since we don't have to explicitly list all
unknown characters.

Lex any unknown character as an UNDEFINED_SYMBOL

---

poincare/include/poincare.h
poincare/include/poincare/dynamic_hierarchy.h
poincare/include/poincare/expression.h
poincare/include/poincare/expression_array.h
poincare/src/bounded_static_hierarchy.cpp
poincare/src/expression.cpp
poincare/src/static_hierarchy.cpp

Before, it was a method of Expression and returned a static array.
However, we have no guarantee that the function will not be called again
while the array is being used, thus erasing the previous array.
Change-Id: Ic640cee7edeb3b2805febde6287414a1497a5b4c

[poincare] ExpressionArray is now a class, not a method.

---

apps/home/controller.cpp

Some very minor change, almost futile, to the Home application.
Like in many handheld devices, when in the Home application, if you push the Home (or Back) button, you will select the first page/application.

Very small feature : In Home application, Home or Back button select Calculation

---

ion/src/device/device.cpp

The recent enabling of instruction and data cache increase the device performance which forces to recalibrate the delay methods

[ion] Re-calibrate the delay methods (msleep and usleep) 

---

apps/sequence/list/sequence_toolbox.cpp

In the sequence toolbox, update the extra-cells when updating the hold layout to avoid unvalid read

[apps] Sequence: fix unvalid read

---

build/targets.emscripten.mak
build/toolchain.emscripten.mak

Use a whitelist to reduce the impact of Emterpreter, and get rid of EMTERPRETIFY_FILE

Emterpretify

---

build/toolchain.emscripten.mak
ion/include/ion/events.h
ion/src/emscripten/events_keyboard.cpp
ion/src/emscripten/events_keyboard.h
ion/src/emscripten/simulator.html

* Much, much lower CPU usage by using `emscripten_sleep` in a tight loop
* Ability to push multiple events at once
* Ability to push a key or an event (modifiers discarded in the second case)
* Only redraw when processing the last event

[emscripten] Use an event queue

---

apps/sequence/graph/curve_view_range.cpp
apps/shared/interactive_curve_view_range.cpp

05055c387f8b0535062bee4a0d5b93ddd86c8d2a seems to have broken the exam mode.
1. Open the native simulator
2. Try to enable Exam mode
3. The simulator crashes
```
epsilon.elf: apps/shared/interactive_curve_view_range.cpp:170: virtual void Shared::InteractiveCurveViewRange::setDefault(): Assertion `m_delegate' failed.
```
This is also present in the official Emscripten simulator at https://www.numworks.com/simulator/. On an actual device, the calculator simply reboots.

[apps] Fix exam mode

---

python/port/mpconfigport.h

Otherwise it breaks when upgrading uPy. Faulty commit 4011290.

Enable the urandom module in mpconfigport.h, not in uPy

---

apps/hardware_test/serial_number_controller.cpp
apps/settings/sub_controller.cpp
ion/include/ion.h
ion/src/device/Makefile
ion/src/device/base64.cpp
ion/src/device/base64.h
ion/src/device/bench/command/mcu_serial.cpp
ion/src/device/device.cpp
ion/src/device/device.h
ion/src/device/usb/Makefile
ion/src/device/usb/calculator.cpp
ion/src/shared/dummy/serial_number.cpp
ion/src/simulator/Makefile
ion/src/simulator/init.cpp

Also, expose serialNumber() in Ion and keep "copySerialNumber" in
Ion::Device. This allows the DFU bootloader to remain .bss-free.

[ion] Encode the serial number in Base64

---

poincare/src/print_float.cpp
poincare/test/convert_expression_to_text.cpp

floor(abs(100000))*pow(10,-5)= 0.9999999 instead of 1

[poincare] PrintFloat: fix error due to float/double precision

---

build/defaults.mak

Using `-O0` with the device target results in an ELF binary so bloated it won't fit in flash. Use saner `-Og` instead for debug builds.

Use saner default debug flags

---

ion/src/device/usb/dfu_interface.cpp

The PG bit in FLASH.CR stayed true, which allowed unwanted flash write operations outside of DFU commands.

Fix flash access

---

apps/sequence/graph/graph_view.cpp

(2 dots per pixel instead of 5)

[sequence] Decrease sequence graph resolution

---

escher/src/transparent_view.cpp

(because superviews have not been filled yet). Rather use m_frame.

[escher] Fix transparent view: absolute origin can be undefined

---

apps/sequence/sequence.cpp

Before, it was always u0 and u1.

[apps/sequence] Fix first/second term index display.

---

apps/calculation/calculation.cpp
apps/calculation/calculation.h
apps/calculation/history_controller.cpp
apps/calculation/history_view_cell.cpp
apps/calculation/history_view_cell.h

Do not memoize the expression layouts but the expressions final heights to avoid overflowing the heap. The expression layouts are kept in the cell which are fewer then the number of calculations.

[calculation] Fix heap overflow

---

ion/src/shared/dummy/keyboard.cpp

The scan of keyboard in Blackbox should indicate that no key is pressed in order to avoid interrupting all simplification

[ion] Blackbox keyboard scan

---

apps/calculation/edit_expression_controller.cpp
apps/calculation/edit_expression_controller.h
apps/shared/expression_layout_field_delegate.cpp
apps/shared/expression_layout_field_delegate.h
escher/include/escher/expression_field.h
escher/include/escher/expression_layout_field.h
escher/include/escher/expression_layout_field_delegate.h
escher/include/escher/input_view_controller.h
escher/src/expression_layout_field.cpp
escher/src/input_view_controller.cpp

Warning: in ExpressionField: the serialized layout is not guaranteed to
be small enough to fill in the text buffer

[escher] ExpressionLayoutFieldDelegate should not take a text as parameter but a layout

---

poincare/src/layout/char_layout.cpp
poincare/src/layout/char_layout.h

Avoid adding multiplication sign between Sto and another expression without breaking other writeTextInBuffer ('1+x+x^2+x^3')

[poincare] Fix fix CharLayout

---

apps/statistics/histogram_controller.cpp

Even if the bar parameters has not changed, the maximal size might differ.

[statistics] Recompute the histogram range parameters if the store has changed

---

poincare/src/power.cpp

Otherwise, it causes bug when trying to reduce to same denominator.
For example:
In Calculation app, type:
`'6' OK,
'Y-ans/(ans*ans*ans*ans*ans)', OK
OK
OK
OK`
--> crash

[poincare] Rational Power: always reduce p^(-1) if p rational

---

poincare/src/layout/expression_layout.cpp

When collapsing sibling layouts, isCollapsable should be called even if
forceCollapse is true, in order to update the number of open
parentheses.
This fixes the bug: (1+(21)^2), then Event::Divide

[poincare] Fix layout collapsing

---

kandinsky/Makefile

Since freetype2 version 2.9.1 freetype-config has been deprecated and is not installed by default anymore: https://sourceforge.net/projects/freetype/files/freetype2/2.9.1/
Fixes #502.

[kandinsky] use pkg-config instead of freetype-config

---

apps/code/Makefile
apps/code/editor_controller.cpp
apps/code/editor_view.cpp
apps/code/editor_view.h
apps/code/python_text_area.cpp
apps/code/python_text_area.h
escher/Makefile
escher/include/escher/solid_text_area.h
escher/include/escher/text_area.h
escher/include/escher/text_field.h
escher/include/escher/text_input.h
escher/src/solid_text_area.cpp
escher/src/text_area.cpp
escher/src/text_field.cpp
escher/src/text_input.cpp

Following a very interesting PR by @zardam #435 , here's an updated version.
* TextArea is not tied to Python anymore
* The Python heap is dynamically allocated (it risked overflowing the stack)
* If not enough memory is available, it falls back to black and white drawing
* Uses the MicroPython's lexer, thanks to a very nice PoC by @zaradam
* Reuses and extends TextArea's dirty tracking
* Does syntax-highlighting on a per-line basis (avoids re-rendering the whole screen)
* The color theme that matches the one on https://workshop.numworks.com
Shortcomings:
* Doesn't do anything special for builtins because those aren't recognized by uPy's lexer.
* Doesn't treat function definition differently (because we're using a lexer and not a parser).

Python syntax highlighting

---

apps/calculation/calculation.cpp

Avoid getting sqrt(2)/2 = 0.999906 (wrong) instead of cos(pi/4) = 0.999906

[calculation] Do not re-simplify exact output

---

ion/src/emscripten/display.cpp

This gives the opportunity to run arbitrary JS code after each display refresh

[emscripten] Add a Module.onDisplayRefresh callback

---

apps/statistics/box_controller.cpp
apps/statistics/box_view.cpp
apps/statistics/box_view.h
apps/statistics/multiple_boxes_view.cpp
apps/statistics/multiple_boxes_view.h

Problem:
In Statistics, select a box view then press back to select a tab: the
previously seleted box stays colored even though it is unselected.

[apps/stats] Fix color problem when unselecting the box views

---

apps/sequence/list/list_controller.cpp
apps/sequence/list/sequence_toolbox.cpp
apps/sequence/list/sequence_toolbox.h

When scrolling from "v(n+1)" to "abs(x)", the "v(n+1)" cell disappeared

[poincare] Fix SequenceToolbox special cells display when scrolling

---

apps/on_boarding/update_controller.cpp

Build with ON_BOARDING_APP=1 and power off the calculator. When plugging
the calculator, the device did not enter the DFU mode nor quits exam
mode.

[apps] Fix pop up clash when plugging the device

---

escher/src/switch_view.cpp

This pull request invert the handle position in SwitchView. It intends to make the switch a bit less confusing for new users, as it look more like switches on Android or iOS or other platforms.
Off state:
On state:

Inverted SwitchView handle position

---

escher/src/button.cpp

Changed active button color to YellowDark

---

apps/code/python_text_area.cpp

Some variables were declared as int while they are size_t. As we try to compare
them to unsigned values, a warning was raised (comparison of integer expressions
of different signedness).

Fix warnings about comparing different signedness

---

apps/regression/graph_controller.cpp
apps/regression/graph_controller.h
apps/shared/double_pair_store.cpp

Bug: in Regression, add points (1, 3), (2,3).
Go to the graph, go back to the data and add the point (0,0). Go back to the graph, the regression coefficients were not updated.
This was due to a problem in DoublePairStore::storeChecksum

Fix regression update on changing data

---

apps/sequence/list/list_controller.cpp

Hello,
I found a bug in Sequences, if you make a Un+1 sequence, the edit expression field is not erased between Un+1 and Un if you edit Un with any key except OK and Exe.
Here is an example:
This pull request intends to fix that.

[Sequences] Edit expression field is not erased in some cases

---

python/src/py/parsenum.c

This is fixed in Micropython project by commit b768cc6ca8ed6d7430b86dc7ccb9ee2391b3a251.

[python] Fix bug in Micropython when parsing const char * in float/double

---

apps/code/editor_controller.cpp

The area buffer given to the EditorController has a reserved char representing the importation status. We thus cannot use strcpy because null termination might be triggered by the importation status before the end of the script content.

[code] Fix EditorController: cannot use strcpy when the first char is a flag that can be 0

---

apps/code/variable_box_controller.cpp

[python] Don't add underscore-prefixed items to the var menu

---

poincare/src/decimal.cpp

Before, we used an unsigned mantissa and needed to set the sign
afterwards, but with the signed mantissa we must not do this.

[poincare] Fix Decimal::templatedApproximate

---

ion/src/shared/crc32.cpp

Change crc32 implementation for simulator, blackbox and emscripten to avoid alignment issue on emscripten platform.

[ion] crc32 implementation

---

apps/statistics/multiple_data_view.cpp

To see this pixel row, go in the statistics app, add 3 series, go in the Histogram tab, then switch off and on the calculator. The pixel row on top of the banner view has random colours.

[apps/stats] Fix pixel row not drawn when there are 3 histograms

---

build/toolchain.emscripten.mak
python/port/helpers.cpp
python/port/helpers.h
python/port/mod/time/modtime.cpp

* Mark `micropython_port_should_interrupt` and `micropython_port_interruptible_msleep` as async symbols in Emscripten
* Make `micropython_port_interruptible_msleep` available in a helper

[python] Clean the time module

---

apps/calculation/calculation.cpp

If the results are equal but their layouts not, because of the number of
significant digits for instance, display both the equal and approximate
results.

[apps/calculation] Fix display exact and approx results

---

apps/calculation/history_controller.cpp
apps/calculation/history_controller.h
apps/calculation/history_view_cell.cpp
apps/calculation/history_view_cell.h
apps/calculation/selectable_table_view.cpp
apps/calculation/selectable_table_view.h

In SelectableTableView::selectCellAtLocation, we call 'tableViewDidChangeSelection'
before scrolling. Therefore, the cell with updated with the right selected subview
is not the one drawn... To solve this issue, we keep the selectedSubview ('model')
in the HistoryController instead of in the limited-lifespan view.

[calculation] Bug in the subview selected with heigh cells

---

apps/code/sandbox_controller.cpp
apps/suspend_timer.cpp

The sandbox was not exited when the device suspended because of a long
time without use. When the device was powered on again, a blank sandbox
was displayed.
The sandbox also prevented USB enumeration.

[apps] Sandbox handles/absorbs only keyboard events (except Home, OnOff)

---

apps/regression/store.cpp

Data set:
X1: 8 9 10 10
Y1: 2 5 1  2
X2: 10 12 5
Y2: 2  0  8
Navigating vertically on the (10, 2) point goes into a loop

[apps/regression] Fix vertical navigation if 2 series have same point

---

poincare/src/power.cpp

std::pow is more precise on doubles than on complexes, we rather use the
double version when possible

[poincare] Power: fix approximation precision

---

poincare/src/integer.cpp

Take the sign into account even for infinite values

[poincare] Fix Integer::approximate

---

apps/sequence/sequence.cpp
apps/shared/expression_model.cpp
apps/shared/poincare_helpers.h

Revert: To approximate an expression, it is more precise to approximate its simplified form than its reduced form. Indeed, we want to minimize the number of nodes in the expression before approximating.
For instance, a/b has fewer nodes than a*b^-1.

[shared] Use Simplify instead of Reduce

---

apps/shared/storage_expression_model.cpp
poincare/include/poincare/expression.h
poincare/src/expression.cpp

To approximate an expression, it is more precise to
approximate its simplified form than its reduced form. Indeed, we want
to minimize the number of nodes in the expression before approximating.
For instance, a/b has fewer nodes than a*b^-1.

[poincare] Revert: Use Simplify instead of Reduce II

---

apps/shared/storage_expression_model_list_controller.cpp
apps/shared/storage_expression_model_list_controller.h
apps/shared/storage_function_list_controller.cpp
apps/shared/storage_function_list_controller.h

When there were more than 13 functions in the Graph app, scrolling was very slow near the bottom of the list.

Improve function scroll speed when many functions

---

poincare/src/complex_cartesian.cpp

The assertions that the real and imaginary parts are real can be false due to double lack of precision. We escape these cases by returning an undefined approximation.

[poincare] ComplexCartesian: fix approximation

---

python/port/mod/turtle/turtle.cpp
python/port/mod/turtle/turtle.h

This reduces rouding errors, such as:
setHeading(0)
right(1)
heading() -> gives -1.00...01

[python/turtle] Store the heading in degrees with no k_headingOffset

---

apps/shared/curve_view.cpp

For instance, in Probability app, draw a standard normal law. The zero
was top left of the screen...

[apps/curve_view] Fix zero label position

---

.travis.yml

This may not be the most useful PR, but allowing Makefile parallelization can save few seconds on the build time on Travis-CI (as shown on [https://docs.travis-ci.com/user/speeding-up-the-build/](https://docs.travis-ci.com/user/speeding-up-the-build/#makefile-optimization))

[travis] Update .travis.yml to allow Makefile parallelization

---

apps/shared/expression_field_delegate_app.cpp

Layouts have two potential serializations. For example,
HorizontalLayout(CharLayout(2), CharLayout(a)) can be serialized as:
"2a" and "2*a". In layoutFieldDidReceiveEvent, we want to check that the
longest serialisation is bounded by maxBufferSize. (We could have used
Layout::serializeParsedExpression but we don't to avoid parsing the
expression twice)

[apps/shared] Fix ExpressionFieldDelegateApp::layoutFieldDidReceiveEvent

---

poincare/src/power.cpp

Rule is applied if:
- a > 0
- in Real: when b and c are integers
- in other modes: when c is integer

[poincare] Fix mis-implementation of (a^b)^c -> a^(b*c)

---

apps/calculation/calculation.cpp

[apps/calc] approximateOutput handles unparsable m_approximateOutputText

---

apps/regression/model/model.h

The exponential regression on the following data now works:
1 120000
3 130000
6 150000
8 160000

[apps/regression] Increase the iterations limit to compute a regression

---

escher/include/escher/layout_field.h
escher/src/layout_field.cpp
poincare/Makefile
poincare/include/poincare/condensed_sum_layout.h
poincare/include/poincare/fraction_layout.h
poincare/include/poincare/horizontal_layout.h
poincare/include/poincare/integral_layout.h
poincare/include/poincare/layout.h
poincare/include/poincare/layout_node.h
poincare/include/poincare/sequence_layout.h
poincare/src/fraction_layout.cpp
poincare/src/horizontal_layout.cpp
poincare/src/layout_node.cpp
poincare/test/helper.cpp
poincare/test/helper.h
poincare/test/layout_cursor.cpp

Clean the code to position the cursor when inserting a layout. This removes a dirty inclusion of apps/i18n.h in Escher

Fix layout field cursor position

---

apps/regression/Makefile
apps/regression/linear_model_helper.cpp
apps/regression/linear_model_helper.h
apps/regression/model/exponential_model.cpp
apps/regression/model/exponential_model.h
apps/regression/store.cpp
apps/regression/test/model.cpp

Fix #969
Epsilon's implementation of Levenberg-Marquardt regression algorithm cannot find the optimal parameters of an exponential regression for samples (added to the test suite) which actually admit an exact fit.
In fact, for the sample generated by y=e^(-x) with x ranging from 0 to 10, we observed that this implementation finds a pretty reasonable solution in that the error function is quite small (0.15...) and that the gradient of the error function is smaller than the precision of Poincare, so that the algorithm stops there, although the estimated parameters (1, -182) are far from the optimal ones. Indeed, the error function is small in a wide region in which its variation are imperceptible.
In any case, it is more satisfactory for our purpose to find the optimal solution for samples …

Explicit exponential regression

---

poincare/include/poincare/integral.h

Fix #987
The `Poincare::IntegralNode::adaptiveQuadrature` method approximates recursively the integral of a given function, more and more accurately. It stops when
* either the approximation error is smaller than a given tolerance
* or the number of iterations reaches a given maximum, where it returns `NaN`.
At each iteration, if the approximation error is not satisfactory, it divides the integration interval in two equal pieces and calls itself on each subinterval, expecting that their respective errors will both be smaller than the initial tolerance.
If the bounds of the integral are X and Y and the maximal number of iterations is N, the smallest subinterval size looks like (X - Y) / 2^N.
The more a function varies quickly (such as x -> x^a with a in (0,1) in the neighborhood of 0), the …

Increase the max number of iterations to approximate an integral

---

apps/solver/solutions_controller.cpp

The layout for delta=b^2*4ac did not appear properly

[apps/solver] Fix string length computation

---

apps/statistics/histogram_controller.cpp
ion/Makefile
ion/include/ion/unicode/utf8_helper.h
ion/src/shared/unicode/utf8_helper.cpp
ion/test/utf8_helper.cpp

Fix a display bug in the banner view of statistics
Scenario:
Scientific mode, statistics app with data:
10 - 1
20 - 5
30 - 4
40 - 3
50 - 1
Display the histogram, there are problems in the banner view

Glyph length

---

escher/include/escher/text_input_helpers.h
escher/src/text_area.cpp
escher/src/text_input_helpers.cpp
ion/include/ion/unicode/utf8_helper.h
ion/src/shared/unicode/utf8_helper.cpp

We used a small buffer to preprocess a text to insert in text area (add
indentation, remove empty code points, compute the next cursor location),
but the size of this buffer was sometimes too small and caused a crash.
Now we do all the text modification in place in the text area buffer.

[escher/text_area] Fix text indentation handling

---

apps/code/python_toolbox.cpp

We used an array that was out of scope in PythonToolbox.

[code] Fix 'use address after scope' issue

---

apps/sequence/sequence.h
apps/shared/cartesian_function.h
apps/shared/function.h

If these classes are padded, we lose space in the Storage and the
Storage::checksum is computed on uninitialized values (corresponding to
the padding memory spaces)

[apps] Force packing classes of objects contained in the Storage

---

apps/code/editor_controller.cpp
escher/include/escher/text_area.h
escher/include/escher/text_field.h
escher/include/escher/text_input.h
escher/src/text_area.cpp
escher/src/text_field.cpp
escher/src/text_input.cpp
ion/include/ion/unicode/utf8_decoder.h
ion/include/ion/unicode/utf8_helper.h
ion/src/shared/unicode/utf8_decoder.cpp
ion/src/shared/unicode/utf8_helper.cpp
ion/test/utf8_decoder.cpp

Fix Left/Right/Backspace on special UTF8 glyphs ('é' for instance)

Fix cursor navigation on utf8

---

poincare/src/code_point_layout.cpp

The user can now write intuitively 1/2 * 3/4
This fixes #1028

[poincare] Better collapsing of fractions

---

escher/src/layout_field.cpp

Scenario : In calculation, write 10/7, enter
Go up, press OK on 10/7 -> the cursor is not on the right of the layout

[escher/layout_field] Fix cursor position when inserting layout

---

apps/code/console_controller.cpp

The command "squares()%input()" followed by text, OK, and a backspace
event broke an assertion on the consoleStore number of lines.

[apps/code] Fix sandbox and input clash

---

apps/code/console_edit_cell.cpp
apps/code/console_edit_cell.h
apps/code/menu_controller.cpp
apps/graph/list/list_controller.cpp
apps/graph/list/text_field_function_title_cell.cpp
apps/shared/buffer_text_view_with_text_field.cpp
escher/include/escher/editable_field.h
escher/include/escher/layout_field.h
escher/include/escher/text_field.h
escher/src/expression_field.cpp
escher/src/text_field.cpp

Fix bug: OK handling on function list in linear mode did not copy the function expression into the textfield before editing

[escher] TextField: call reinitDraftBuffer after edition is complete to avoid erasing text that is required later

---

ion/src/device/n0110/drivers/board.cpp
ion/src/device/shared/usb/dfu_relocated.cpp
liba/include/stdbool.h

When building with LTO (which is on by default), the compiler makes sure all type definitions are coherent. We had a few mismatches (`char` vs `_Bool`, `void *` vs `char *`).
Mismatching types had the same size, so in practice this shouldn't have had any negative impact aside from the nasty warnings at link time.

Remove LTO warnings

---

poincare/include/poincare/norm_cdf2.h
poincare/include/poincare/normal_distribution_function.h
poincare/src/normal_distribution_function.cpp
poincare/test/simplification.cpp

normcdf2(1,2,0,1) was shallowReduced to undef in the Calculation app

[poincare/normcdf2] Fix shallowReduce (mu and var indexes were wrong)

---

poincare/include/poincare/randint.h
poincare/src/randint.cpp
poincare/test/simplification.cpp

When reducing f(x)=randint(floor(x),floor(10x)), the randint
simplification would give undef because x is undefined at the time of
the reduction

[poincare/randint] Fix randint simplification

---

poincare/include/poincare/matrix_layout.h
poincare/src/matrix_layout.cpp

Delete a matrix layout line only when deleting the left empty layout of an empty line.
This way, one can more easily edit matrices, for instance in the graph app for parametric functions.
Scenario:
f(t) = | t | and try to replace the t with 1
|2t|

Fix matrix line deletion

---

poincare/src/power.cpp
poincare/test/helper.cpp
poincare/test/helper.h
poincare/test/simplification.cpp

Reducing should happen after replacing the expression in its hierarchical context.
Fix sum(1/n, n, 1, 5) reducing with no symbolic computation.

[poincare] Power::shallowReduce

---

poincare/src/matrix_layout.cpp

[•]
[•]
[2] will be serialized like [2].
[•]
[•]
[•]
This way, if a user inputs a column matrix and then switches to a line
matrix without properly deleting each empty row, it is serialized
correctly.

[poincare/matrix_layout] Do not serialize the first and last empty lines

---

apps/graph/graph/graph_controller.cpp

The default range is [-10;10], but if all the functions are cartesian
and defined in a smaller range (for instance [-0.1,0.1]), use that
smaller range.

[apps/graph] If only cartesians, use domains range if < default range

---

apps/regression/graph_controller.cpp
apps/regression/graph_controller.h
apps/shared/round_cursor_view.h

Scenario:
double x[numberOfPoints] = {0.0, 0.975, 1.97, 2.945, 3.971, 4.887, 5.924, 6.964, 7.979, 8.974, 9.998};
double y[numberOfPoints] = {-23.784, -23.322, -28.322, -18.422, -4.813206, 7.146241, 16.631, 16.632, 9.209189, -6.050863, -19.659};
Quadratic regression, navigate on the points then go on the
regressioncurve -> there is a drawing glitch

[apps/regression] Fix cursor redrawing when changing cursor type

---

poincare/include/poincare/decimal.h
poincare/src/decimal.cpp
poincare/test/expression.cpp

Now, Decimal node "1.000E3" is not equal to Decimal node "1E3" node anymore.
This prevents from using double comparison (which is sometimes wrong due to
double precision) to implement decimal comparison.

[poincare] Decimal: change order definition on Decimal expression

---

apps/shared/range_1D.cpp
poincare/src/derivative.cpp
poincare/src/print_float.cpp

This avoids precision issues when computing the number of digits of a number.

[poincare][apps/shared] Use IEEE754::exponentInBase10 instead of std::floor(std::log10())

---

poincare/src/derivative.cpp
poincare/test/approximation.cpp

Fix a derivative error:
- Stop the iterative riddersApproximation if the error starts increasing
- h should be superior to 10 epsilon
- if the result is close to 0, be less restrictive on the error/result ratio
Fixes #1150 
The derivative now displays -2E-11 in graph for f(x) = -1/3 x^3 + 6x^2 - 11x - 50 and "go to" x = 11.
To display 0, we should implement the derivative reduction

Fix derivative bug

---

ion/src/device/shared/drivers/board.cpp
ion/src/device/shared/drivers/timing.cpp
ion/src/device/shared/drivers/timing.h
python/port/helpers.cpp

millis() was quite false because we change the HCLK frequency in msleep.
This is mitigated by also changing the Systick frequency in msleep, but this provokes a small drift, visible in the Python sleep -> This method was changed to generate less frequency changes

Calibrate SysTick

---

poincare/src/addition.cpp
poincare/src/approximation_helper.cpp
poincare/src/binomial_coefficient.cpp
poincare/src/complex_cartesian.cpp
poincare/src/confidence_interval.cpp
poincare/src/conjugate.cpp
poincare/src/decimal.cpp
poincare/src/equal.cpp
poincare/src/expression.cpp
poincare/src/factor.cpp
poincare/src/factorial.cpp
poincare/src/layout_helper.cpp
poincare/src/logarithm.cpp
poincare/src/matrix.cpp
poincare/src/matrix_complex.cpp
poincare/src/matrix_dimension.cpp
poincare/src/matrix_trace.cpp
poincare/src/multiplication.cpp
poincare/src/n_ary_expression.cpp
poincare/src/nth_root.cpp
poincare/src/number.cpp
poincare/src/opposite.cpp
poincare/src/parsing/parser.cpp
poincare/src/power.cpp
poincare/src/prediction_interval.cpp
poincare/src/rational.cpp
poincare/src/round.cpp
poincare/src/sign_function.cpp
poincare/src/store.cpp

When returning a subclass of an Expression as an Expression, make sure
to use std::move, otherwise the compiler cannot proceeed to copy
ellision.

[poincare] Use std::move when needed

---

apps/code/console_controller.cpp

When scrolling up in the python shell history, `selectedCell` could be NULL.
Tested on the simulator.

[apps] [code] Fix nullptr deref (fix #1176)

---

build/toolchain.android.mak
ion/src/simulator/android/build.gradle

* Match NDK version to what's specified in the APK (`minSdkVersion`)
* Bump compileSdkVersion and targetSdkVersion

Improve Android builds

---

poincare/src/power.cpp
poincare/test/simplification.cpp

(a^b)^c -> a^(b*c)
This rule is not generally true: ((-2)^2)^(1/2) != (-2)^(2*1/2) = -2
This rule is true if:
- a > 0
- c is an integer
Warning 1: in real mode only c integer is not enough:
ex: ((-2)^(1/2))^2 = unreal != -2
We escape that case by returning 'unreal' if the a^b is complex.
Warning 2: If we did not apply this rule on expressions of the form
(a^b)^(-1), we would end up in infinite loop when factorizing an addition
on the same denominator.
For ex:
1+[tan(2)^1/2]^(-1) --> (tan(2)^1/2+tan(2)^1/2*[tan(2)^1/2]^(-1))/tan(2)^1/2
--> tan(2)+tan(2)*[tan(2)^1/2]^(-1)/tan(2)
--> tan(2)^(3/2)+tan(2)^(3/2)*[tan(2)^1/2]^(-1)/tan(2)^3/2
--> ...
Indeed, we have to apply the rule (a^b)^c -> a^(b*c) as soon as c is -1.

[poincare] Power: always reduce (a^b)^(-1)

---

poincare/include/poincare/symbol.h
poincare/src/symbol.cpp

This makes consistent 2x and 2θ (sign omission in both cases).

[poincare] Fix multiplication symbol before Symbol Expression

---

ion/src/simulator/web/simulator.html

Using SDL2, we don't need to preventdefault on space/arrow keydown
And if we do, we don't get "space" events in the simulator.

[ion/simulator/web] Remove a hack

---

apps/shared/values_controller.cpp

This fixes a crash that happens when deleting a row by clicking on "Backspace" on an evaluation cell

[apps/shared] ValuesController: fix didChangeCell to reload all cells corresponding to the abscissa cell

---

build/targets.device.n0110.mak

In NumWorks DFU mode, execution jumps at the end of the stack, which is where we upload the flasher. The flasher is not required when NumWorks DFU mode is working.

[build] Fix target %.dfu for N0110: avoid downloading flasher on addresses that are being executed 

---

ion/src/shared/storage.cpp

Don't forget to update the CRC32 of the record
Scenario : New funciton f(x) = 1, change it to parametric, rename it
a(t), creae a new function -> instead of being empty, it is has a
"ghost" value of [t 1].
Fixes #1213

[ion/storage] Fix memoization dirtying when renaming a record

---

apps/sequence/values/values_controller.cpp
apps/sequence/values/values_controller.h

This fixes the scenario:
Add a sequence, go to the Table then click on setTheInterval -> it
displayed Xstart Xend instead of Nstart Nend
Fixes #1214

[apps/sequence] Set the Nstart/Nend messages at construction

---

apps/on_boarding/power_on_self_test.cpp

Green is used to indicate end-of-charge, so we put the POST led in white
so there is no confusion

[apps/on_boarding] If POST are OK, the led is white

---

ion/src/device/n0110/drivers/board.cpp

This fixes the bug happening on a N0110 device built with on-boarding:
- Enter the function `20cos(x)+10` in the function application
- Go to the graph
- Go to the zoom menu
- Click 3 times on `minus` key
- The screen went black...

[ion] N0110 board: fix MPU configuration on FMC memory bank

---

apps/apps_container.cpp

Push a white screen before fetching the examm mode, as this fetch takes
some time and the screen noise becomes visible on a n0100 when
downloading a new software.

[apps/apps_container] Fix screen noise before the logo on n0100

---

ion/src/device/n0110/drivers/cache.cpp

__asm volatile("nop") creates a memory barrier that prevents a crash on
the flasher.
Scenario: On the n0110, build flasher.bin, flash it at 0x20030000, build
bench.bin, flash it using the flasher at 0x20008000 -> the flasher cannot
make the device jump to the bench

[ion/cache] Add missing memory barrier

---

ion/src/device/n0100/drivers/config/external_flash.h
ion/src/device/n0110/drivers/config/external_flash.h
ion/src/device/n0110/drivers/config/usb.h
ion/src/device/shared/drivers/external_flash.cpp
ion/src/device/shared/drivers/external_flash.h

Instead of 128 sectors of 64K, there are now 8 sectors of 4K, 1 of 32K
and 127 of 64K. This makes a more finely erasable flash, which is needed
for the exam mode.

[ion/external_flash] Finer flash sectors

---

poincare/include/poincare/approximation_helper.h
poincare/src/approximation_helper.cpp
poincare/src/great_common_divisor.cpp
poincare/src/least_common_multiple.cpp
poincare/test/approximation.cpp

This fixes the following bug: when entering the sequence u(n) = gcd(n-2,n^2+n+3), in the value table, u(1) = -1 instead of 1.

Fix gcd and lcm approximation

---

apps/calculation/history_controller.cpp
apps/calculation/history_controller.h
apps/calculation/history_view_cell.cpp
apps/calculation/history_view_cell.h
apps/shared/scrollable_exact_approximate_expressions_view.cpp
apps/shared/scrollable_exact_approximate_expressions_view.h

This resolves two bugs:
- Add "1" to the calculation history. Go up and then go left, the selection is on an invisible layout.
- Add multiple times the calculation "1.2" to the history. Go up, the selection is on the left expression instead of the right one.

Calculation fix selection issues

---

apps/shared/expression_model.cpp
escher/src/text_field.cpp

Fix a serialisation problem.
Scenario: Create a new sequence which is the multiplication of a lot of
imaginary i. Save it (many multiplication sign are added), then try to
edit it again, in linear edition mode: the text overflows the buffer. If
we still copied it, it might get copied until the middle of a code point,
which would make the UTF8Decoder crash afterwards.

Fix expression serialization in lists

---

apps/calculation/history_controller.cpp
apps/calculation/history_view_cell.cpp
apps/calculation/history_view_cell.h

Reset history cell memoization when reloading table. Otherwise, the Poincare pool store useless layouts for cells that aren't displayed.
This fixes the following issue: input "(transpose([1 2 3 4 5 6][1 2 3 4 5
6])^8", the computation works, clear the history, input the same
calculation again, it fails with a memory error.

[apps/calculation] Improve the upkeeping of Poincare pool

---

poincare/src/function.cpp

Faulty scenario:
Equation x+y=f(0) without defining any variable

[poincare/function] Fix getVariables

---

apps/shared/interactive_curve_view_range.cpp

Scenario : f(x)=8x, scroll to the right until the window range has
changed, then set the preadjustment to default -> the x change had no
impact on the yRange because we did not set the yAuto before doing the
changes.

[apps/interactive_curve_view_range] Recompute yRange after setDefault

---

apps/statistics/histogram_controller.cpp

The OK button already does it.

[apps/statistics] EXE should open the histogram param controller

---

python/port/mod/ion/modion.cpp

So that an infinite loop of keydown can be interrupted

[python/modion] Allow interruption of modion_keyboard_keydown

---

apps/code/console_controller.cpp

Otherwise the first responder becomes the console edit line, and events
(such as Toolbox) are not intercepted by the sandbox anymore.

[apps/code] Do not refresh the print if the sandbox is displayed

---

apps/regression/graph_controller.cpp
apps/regression/graph_controller.h

Fixes a bug in 'Prediction given X/Y' menu where the RoundCursorView's underneath pixels were drawn after text field finishes editing.
Scenario:
Enter a quite generic data
X1  Y1
1   0
2   0
3   0
In the graph view, select the regression curve and move the cursor as close as possible to the left or right edge of the view.
Press OK and enter the 'Prediction given X/Y' menu.
Alter the value in the text field, say 0.
Press the down arrow.
Observe that a piece of curve has been drawn.

Regression round cursor view bug

---

ion/src/device/shared/usb/stack/endpoint0.cpp
ion/src/device/shared/usb/stack/endpoint0.h

The return type of the function needs to be wider so the -1 error value
could fit.
Fixes #1335

[ion] Fix error check in the USB stack

---

apps/code/console_controller.cpp

Otherwise, we need to put in the whitelist all methods that might call
printText, which are a lot.
This reverts #1321 on the web emulator, we will need to fix that.

[apps/code] printText should not be asynchronous in emscripten

---

poincare/include/poincare/expression.h
poincare/src/expression.cpp
poincare/src/solver.cpp
poincare/test/function_solver.cpp

When looking for curve intersections or a function's inverse images, moving the cursor to the left can give unsatisfying results, whereas moving the cursor to the right does better.
Scenario:
Define the function f(x) = sin(x+0.0001) and look for the inverse images of 0, thanks to the corresponding menu.
Observe that when navigating the right, the images are always 0, whereas when navigating to the left, the images are close to 0 but not 0.

Fix poincare solver

---

apps/shared/curve_view.cpp
apps/shared/curve_view.h
apps/shared/curve_view_range.h
poincare/include/poincare/expression.h
poincare/include/poincare/unit.h

An integer or float value can not be assigned to, so there is no point
in qualifying it as const.

Remove useless uses of const for return types

---

poincare/src/parsing/parser.cpp
poincare/src/parsing/parser.h
poincare/src/vertical_offset_layout.cpp
poincare/test/parsing.cpp
poincare/test/simplification.cpp

This way there is no parsing confusion when copy pasting the subscript of
a subscript layout

[poincare/vert_off_lay] Subscript layout serializes without _

---

poincare/include/poincare/unit.h

Based on : https://github.com/numworks/epsilon/pull/1367#issuecomment-594035282
- Updated the month to 30 days, and not 30*7 days
- Updated the month to 1 year / 12

Updated the month definition

---

poincare/include/poincare/expression.h
poincare/include/poincare/matrix.h
poincare/src/expression.cpp
poincare/src/matrix.cpp
poincare/src/multiplication.cpp

Scenario: in calculation,
1/matrix(matrix(matrix(matrix(... matrix(1) ... )))) gave kind of a
weird result. These kind of computations also broke the fuzzer.

[poincare/matrix] Forbid nested matrices

---

poincare/src/code_point_layout.cpp

Scenario: Enter `(12/34 * 10)` then press "Divide" -> the numerator of the
division was not the whole parenthesed expression

[poincare/code_point_layout] Fix collapsing

---

apps/sequence/sequence.cpp
apps/sequence/sequence.h
apps/shared/sum_graph_controller.cpp
apps/shared/sum_graph_controller.h
poincare/include/poincare/grid_layout.h
poincare/include/poincare/layout_node.h
poincare/src/layout_node.cpp

Fixes the following bug:
In the graph tab of the Sequence app, compute the sum of the terms of
a sequence from 1 to 9 and then from 1 to 10. The Layout is memoized
after the first time and mispositioned the second time since it is
not recomputed.

Fix sequence sum layout

---

apps/shared/cursor_view.h
apps/shared/round_cursor_view.cpp
apps/shared/round_cursor_view.h
escher/include/escher/transparent_view.h
escher/src/transparent_view.cpp

CursorView's background was not redrawn.
Scenario:
In the Sequences app, say with the sequence u_n = 0, make the x-range large enough (`xmax - xmin > 50`) so that the successive points are very close to each other. Observe that after moving the cursor with left and right arrow keys, the background of the cursor is not redrawn.
The same probably went in the Regression app.

Fix cursor view in sequence

---

poincare/src/parsing/parser.cpp

Scenario that crashed: Type `-log_-()00` in the Calculation app and press enter

Fix log parsing

---

apps/statistics/histogram_view.h

It is unused as HistogramView now inherits Shared::HorizontallyLabeledCurveView

[apps/statistics] Remove unused variable in HistogramView

---

ion/include/ion/events.h
ion/src/shared/events_modifier.cpp
ion/src/simulator/shared/events_keyboard.cpp
ion/src/simulator/shared/keyboard_sdl.cpp
ion/src/simulator/shared/platform.h

This PR fixes two things :
- Detect (some) physical keyboard events with the Python ion module, for the simulator platforms (including web)
- Stop buffering events when they cannot be processed

Get key down events on simulator and fix events buffering

---

poincare/src/arithmetic.cpp
poincare/src/multiplication.cpp
poincare/test/approximation.cpp
poincare/test/helper.cpp
poincare/test/helper.h

This fixes the computation of 1.0092^50*ln(3/2), that returned 0 due to an overflow when computing a LCM.

Fix simplification and approximation2

---

ion/src/simulator/android/Makefile
ion/src/simulator/android/build.gradle

Signing parameters can be passed on the command line, e.g. "ANDROID_SIGNING_STORE_FILE=foobar", or they can be written to a ~/.gradle/gradle.properties file using the "EPSILON_SIGNING_STORE_FILE=foobar" syntax.

[build] Signing android apps is easier

---

apps/solver/equation_store.cpp

Scenario: solve a system with the maximum number of variables -> our
routine to compute the number of variables did not use
k_maxNumberOfVariables, so we ended up adding the same children to the
matrix Ab, which created ghosts, which made the deep reduction crash.

[apps/solver] Fix EquationStore::resolveLinearSystem

---

apps/shared/curve_view.cpp

The labels would not float on the right of the display

[apps/curve_view] Fix typo

---

liba/include/unistd.h
python/port/mpconfigport.h

For some reason it was defined in Python and raised re-def errors

[liba] Define SEEK_CUR

---

apps/Makefile
build/helpers.mk
build/rules.mk
escher/Makefile
kandinsky/Makefile
python/Makefile

Previous the build would fail on macOS if you had an epsilon.elf file in
at the root of the project. Indeed, the %.elf -> %.bin rule would get
triggered, but this rule should only operate on generated (intermediate)
elf file.

[build] rule_for now takes both "local" and "global" parameters

---

.github/workflows/metrics-workflow.yml
build/metrics/binary_size.py

This PR adds a tool to compare the size of two binaries, and hooks it into the CI system to report it on any incoming PR.

Build size analysis

---

build/device/ram_map.py
build/targets.device.mak

Invoke with `make output/release/device/n0110/epsilon_ram_map.png`

[build/device] Generate a RAM map

---

apps/Makefile
apps/i18n.py
apps/language_de_iso6391.universal.i18n
apps/language_en_iso6391.universal.i18n
apps/language_es_iso6391.universal.i18n
apps/language_fr_iso6391.universal.i18n
apps/language_pt_iso6391.universal.i18n
apps/main.cpp

Fixes #1493
- We removed Default from the Languages list in #1454, which invalidated our algorithm to parse the argument "--language" in apps/main.cpp, which resulted in the bug described in #1493
- This PR cleans said algorithm, so we do not need the dangerous `const char * languageIdentifiers[]` anymore
I added i18n files for the ISO639-1 codes for languages, but those i18n are only built when `EPSILON_GET_OPT=1`, so not for the device
Maybe we should remove the "none" case?

[apps] GET_OPT uses generated i18n language codes to find language

---

python/port/mod/turtle/turtle.cpp

This patch https://github.com/numworks/epsilon/issues/1506

Negative diameter circle turtle support

---

poincare/src/normal_distribution.cpp
poincare/test/approximation.cpp

In the probability app, standard normal distribution, P(-1E99 <=X<=0) was quite false (-0.5).

[poincare/normal_distribution] Fix StandardNormalCumulDistFuncAtAbs

---

apps/calculation/expression_field.h
escher/include/escher/expression_field.h
escher/include/escher/layout_field.h
escher/src/layout_field.cpp

1. Go to the Calculation app
2. Type `123`
3. Now type `456/` and try retrieving the `123` above to make `456/123`.

[Calculation] Allow inserting a past result at the *denominator* of a fraction

---

escher/include/escher/layout_field.h
escher/src/layout_field.cpp

Scenario: Go to the graph app, create f(x) = 1 then create g(x) -> there
is a weird big margin in the edition field

[escher/layout_field] Reset the scroll when clearing the layout

---

apps/shared/interactive_curve_view_controller.cpp
apps/shared/interactive_curve_view_range.cpp
apps/shared/round_cursor_view.cpp
kandinsky/include/kandinsky/size.h

Fixes #1458
The problem only appeared on the device and was not on the macOS simulator due to the different values of FLT_EPSILON: 1e-5 on the device, around 1e-7 on the simulator.
Now the cursor cannot be on the edge of the graph view: panToMakePointVisible and addMargins change the X and Y ranges to put the cursor fully in the view.

Fix graph black trail bug

---

ion/include/ion.h
ion/src/device/Makefile
ion/src/shared/collect_registers.cpp
ion/src/simulator/android/Makefile
ion/src/simulator/ios/Makefile
ion/src/simulator/linux/Makefile
ion/src/simulator/macos/Makefile
ion/src/simulator/shared/collect_registers.cpp
ion/src/simulator/shared/collect_registers_x86_64.s
ion/src/simulator/web/Makefile
ion/src/simulator/windows/Makefile
liba/include/setjmp.h
python/port/port.cpp

The Python garbage collection failed to mark some allocated objects for x86-64 architecture. We used to rely on the setjmp to get the registers values but this was not true for all architectures.

Python garbage collection

---

apps/shared/parameter_text_field_delegate.cpp

In this commit, there was a small oversight in https://github.com/numworks/epsilon/commit/7a4ee746b2a49a090cf920cfe53935ccdea7d607, which caused https://github.com/numworks/epsilon/issues/1570
So this PR fixes #1570

[apps/shared] Fixed a small mistake in parameter_text_field_delegate.cpp

---

.github/workflows/ci-workflow.yml

Later versions of emscripten removed EMTERPRETER option.

[.github/workflow] ci-workflow: fix emscripten version to 1.39.16

---

ion/src/simulator/shared/layout.cpp
ion/src/simulator/shared/main_sdl.cpp

Try to make the calculator's screen fit perfectly on the host's pixel grid. This is **so** much easier on the eyes 😄

[simulator] Make the calculator's screen pixel-perfect

---

apps/calculation/history_controller.cpp

This fixes the following bug: input 1, OK, 1.2 OK, delete the row whose
input is '1' with the selection on the output view. The output of 1.2
does not toggle and it should.

[apps/calculation] HistoryController: reload the subview selection when deleting row

---

apps/shared/toolbox_helpers.cpp

If the commandLength is > than the buffer size, we have to escape at
some point to avoid overflowing the buffer.

[apps/shared] ToolBoxHelpers: don't overflow buffer

---

kandinsky/src/color.cpp
kandinsky/test/color.cpp

This fixes issue #1643 : "White text using draw_string isn't really white/invisible."

Correctly blend identical colors

---

apps/code/console_controller.cpp
python/port/helpers.cpp
python/port/mod/kandinsky/modkandinsky.cpp

Instead of checking interruptions every 20000 calls to `micropython_port_vm_hook_loop`, do it if 100ms have passed since the last check.
This fixes issue #1649 and improves performances for the Kandinsky module's `drawString` and `fillRect` methods.

Put python interruptions on a timer

---

apps/shared/curve_view.cpp

This fixes the following bug: add the sequence, u(n)=2^n. On the graph,
go to "sum of terms" and try to sum terms from 0 to 18 by moving the
cursor. It hangs.

[apps/shared] CurveView: avoid overflowing KDCoordinate

---

ion/src/device/n0100/drivers/config/console.h

[ion] n0100 Console: fix pin alternate function

---

.github/workflows/ci-workflow.yml
.github/workflows/metrics-workflow.yml

Fix the broken CI on Arm targets. See [this issue](https://github.com/numworks/setup-arm-toolchain/issues/5) on the `setup-arm-toolchain` action.

Use semantic branches on setup-arm-toolchain

---

.github/workflows/metrics-workflow.yml

Change-Id: Icfd19cbad5472f6bf81a2a1accb88e79ab7a115b
Triggering on pull_request_target event, the base version of Metrics will always run on future PR, preventing misuse of this workflow.
Additionally, comment is generated using github-script API. We don't need NumWorksBot anymore.

[github/workflows] Update Metrics to remove NumWorksBot

---

escher/image/inliner.c

While debugging something with the inliner, was using ASAN, I saw there was lot of memory leak with this script. I still get some, but they're located in libpng.

[Inliner] Fixed memory leak

---

apps/Makefile

Cherry-pick one commit by @M4xi1m3 from #1784 
I don't think we needed the dependency for tests, we'll see.

[apps] Fixed missing dynamically-generated dependency

---

apps/calculation/test/calculation_store.cpp
poincare/include/poincare/expression_node.h
poincare/src/addition.cpp

This PR fixes https://github.com/numworks/epsilon/issues/1831
When factorizing on a common denominator, the temporary expressions don't have parents, and don't know about `x`'s definition from the integral.
Therefore, symbols should not be replaced with their definition here.
I also added a unit tests.

[poincare/addition] Fix issue with symbolic computation

---

apps/shared/curve_view.cpp

With this change, discontinuous functions will be detected better, so that two dots at each side of the discontinuity are not connected.
This should fix https://github.com/numworks/epsilon/issues/1762

[apps/shared] Improve discontinuity detection with strict comparisons

---

apps/regression/store.cpp

The value of variable meanX was computed in double, but then stored in
another variable x of type float, thus causing a conversion with
potentially a change of value, and then some incorrect comparisons.
Fix #1753.

Fix enumeration of regression points
