poincare/src/factorial.cpp
poincare/test/function.cpp

Factorial was broken when we switch from float to double. I add tests.

[poincare] Repair factorial

---

apps/code/program.cpp

- Was caught by ASan
- Added a static_assert on the length just in case
- Big C strings concats replaced by raw C++ literal for clarity

[apps/code] template program: don't memcpy from beyond the string

---

ion/src/simulator/keyboard/fltkkbd.cpp

[ion] [simulator] more realistic button labels

---

apps/settings/sub_controller.cpp

- Caught by ASan
- The 3 and 4 length were swapped
- It's now using compile-time automatic sizes

[apps/settings] sub controller: fix buffer overflow.

---

apps/calculation/text_field.cpp

Auto insert ans before sto.

---

apps/Makefile
apps/apps_container.cpp
apps/apps_container.h
apps/apps_container_storage.cpp
apps/apps_container_storage.h
apps/calculation/Makefile
apps/code/Makefile
apps/graph/Makefile
apps/main.cpp
apps/probability/Makefile
apps/regression/Makefile
apps/sequence/Makefile
apps/settings/Makefile
apps/statistics/Makefile

This pull request allows to pick (and order) apps at compile-time.
It is a necessary step for #42 and a reimplementation for #73.

Selection of apps at compile-time

---

apps/shift_alpha_lock_view.cpp
ion/include/ion/events.h
ion/src/shared/events_modifier.cpp

This is for [Issue #111 - \[Suggestion\] Shift Alpha Lock changes](../issues/111).
I don't know if this is something the project maintainers think is a good idea or not!

Change shift alpha lock behaviour

---

apps/i18n.cpp
apps/i18n.h
apps/statistics/calculation_controller.cpp
apps/statistics/calculation_controller.h
apps/statistics/store.cpp
apps/statistics/store.h

Add a sample standard deviation in Statistics

Statistics new sigma

---

apps/shared/text_field_delegate_app.cpp

Change-Id: I9efc803edac4103faafb264849bdb9283640a52b

[apps] Clean warnings

---

escher/src/text_area.cpp
liba/include/limits.h

Change-Id: I363dad3c566289a285179a9f26d3a779f0ff812f

[escher] Add behaviour for end and origin events in text area

---

apps/i18n.cpp

Change-Id: Ie1b3dd27bb767d4afae573284311062d27cff0df

[apps] In i18n, change sample standard deviation name in Spanish

---

escher/src/text_area.cpp

Change-Id: If9760bd9082b7e3f8ebea04cef1df63bae39a2a6

[escher] Fix bug due to int32 overflow

---

apps/global_preferences.cpp
apps/on_boarding/language_controller.cpp
apps/on_boarding/language_controller.h
apps/settings/Makefile
apps/settings/language_controller.cpp
apps/settings/language_controller.h
apps/settings/main_controller.cpp
apps/settings/main_controller.h
apps/settings/sub_controller.cpp
apps/shared/Makefile
apps/shared/language_controller.cpp
apps/shared/language_controller.h

The language choice was implemented twice: once in the on-boarding app, and once in the settings app. This pull request merges these two implementations.

Share language settings

---

apps/shared/values_controller.h

[apps] Decrease the abscissa column's width

---

poincare/src/complex.cpp

Change-Id: Ibe819cb38744ea295e6fabe2885b4a2a51d66497

[poincare] Fix layout of undef in polar

---

poincare/src/confidence_interval.cpp
poincare/src/matrix_dimension.cpp
poincare/src/prediction_interval.cpp
poincare/test/function.cpp

Change-Id: I26816c956297c59f8df447be2eec98bd5c0d91d2

[poincare] Fix dimension and interval fluctuations dimensions

---

Makefile

Change-Id: I684a2bcaf1b28b6ff9730294d64f8bd7a068dd1d

Makefile: change version to 1.1.3

---

liba/include/stdlib.h

[liba] Mark abort() as noreturn

---

poincare/include/poincare/symbol.h
poincare/src/symbol.cpp

Change-Id: Ie2bef0ba70f11608fd8aebbfa545f6de2e4872bb

[apps] Avoid calling the deleted copy operator

---

poincare/src/layout/baseline_relative_layout.cpp

Change-Id: I69b32f779f5d5cdc3e5c8b460dfad8286525cea3

[poincare] Fix baseline_relative_layout alignment

---

.gitignore

Otherwise it triggers changes in git

Ignore exe files in git on Windows

---

apps/probability/calculation_controller.cpp
apps/probability/image_table_view.cpp
kandinsky/include/kandinsky/context.h
kandinsky/src/context_rect.cpp

Change-Id: I1c59e34b126aa54819e399d095499758b9e73125

[kandinsky] Fix draw rect

---

ion/src/emscripten/simulator.html

This allows to take pixel-perfect screenshots straight from a web browser.

Add the ability to take a screenshot in the packaged web simulator

---

escher/src/message_table_cell_with_editable_text.cpp

[escher] Fix Valgrind uninitialized read

---

ion/src/emscripten/simulator.html

It actually automatically downloads the screenshot now, as one would expect.

[emscripten] Fix save screenshot feature

---

apps/settings/sub_controller.h

[settings] Minimum of 5 m_cells in Settings::Subcontroller

---

Makefile

Make clena

---

ion/src/emscripten/events_keyboard.cpp

We want to call Termination event on emscripten platform without crashing.

[ion] Fix updateModifiersFromEvent for emscripten

---

apps/code/menu_controller.cpp
apps/code/menu_controller.h

This prevent from saving script whose name is '.py'

[apps] Code: abort script name editing if MenuController exits responder chain

---

python/port/port.cpp
python/port/port.h

This fixes some heavily-parallels build failures

Remove un-needed headers

---

build/toolchain.emscripten.mak
ion/src/emscripten/simulator.html
ion/src/shared/storage.cpp

* Fix unaligned memory accesses
* Fix duplicated events by moving from a's to spans

Fixes for Emscripten

---

build/toolchain.arm-gcc.mak
ion/src/device/usb/endpoint0.h

Change-Id: I41802f79e7103204991edf38dff94b1c0a3a23ea

[build/ion] Remove code used for debug.

---

poincare/include/poincare/power.h
poincare/src/power.cpp
poincare/src/round.cpp
poincare/test/power.cpp

(fix bug 1.00666666666667^60 = undef)

[poincare] Power: do no simplify Power whose result is too big

---

apps/code/editor_controller.cpp

otherwise, the modifications are lost.

Saving Python script when home is pressed

---

apps/code/script_node_cell.cpp
apps/code/script_node_cell.h
apps/code/variable_box_controller.cpp
escher/src/text_area.cpp

In Code::VariableBoxController

[apps/code] Put cursor inside parentheses when inserting function

---

poincare/src/integral.cpp
poincare/test/function.cpp

Stop computing an integral if the evaluation of the function is undef.

Fix integral computation with undef

---

apps/graph/graph/graph_controller.cpp
apps/shared/function_store.cpp
apps/shared/function_store.h

For instance, input f(x)=1/0 and g(x)=1, the graph tab now selects g
correctly

[apps/graph] Fix graph selection when a function is undef

---

ion/src/device/device.h

[ion] Discard outdated comments

---

apps/graph/graph/curve_parameter_controller.cpp

Pressing Right on the second item would not display the submenu.

[apps/graph] Fix curve parameters menu navigation

---

apps/calculation/calculation.cpp
apps/calculation/calculation.h

Delay the overflow of the TreePool

[calculation] No Expression memoization in Calculation:

---

apps/calculation/calculation.cpp
poincare/Makefile
poincare/include/poincare/decimal.h
poincare/include/poincare/expression_node.h
poincare/src/decimal.cpp
poincare/test/decimal.cpp

- Keep the extra 0 entered by user
- Fix Decimal comparison
- Calculation: do not display the exact result if a Float appears

Poincare: Decimal

---

build/toolchain.arm-gcc.mak

If no LTO, at least prune symbols.

[build] LTO flag can be set by user, else it is opposite of DEBUG flag

---

poincare/src/integral_layout.cpp

[poincare] Fix IntegralLayout "dx" rendering position

---

apps/home/controller.cpp
apps/home/controller.h

[home] Fix dirty bottom row of home screen

---

ion/src/device/flash.cpp
liba/include/stddef.h
tests/dfu_test.py

This fixes a few bugs when doing unaligned flash writes

[ion] Support random flash writes

---

build/toolchain.emscripten.mak
ion/src/emscripten/events_keyboard.cpp
python/port/helpers.cpp
python/port/helpers.h
python/port/mpconfigport.h

Allow long-running Python scripts to refresh the display

Emscripten python live drawing

---

apps/statistics/histogram_controller.cpp
apps/statistics/histogram_controller.h
apps/statistics/multiple_data_view.cpp
apps/statistics/multiple_data_view.h
apps/statistics/multiple_data_view_controller.cpp
apps/statistics/multiple_data_view_controller.h

- The banner views of the histogram and the box controllers appear and disappear with selection
- The labels are complete when a series is added

Fix statistics bug

---

escher/src/app.cpp

Instead of calling ModalViewController::displayModalViewController
directly.

[escher] Always use App::displayModalViewController

---

Makefile
build/config.mak
build/scenario/Makefile

Run "make scenario_logger" then "./epsilon_scenario_logger.bin --logAfter 0 < scenario.esc" to create an executable that logs scenario.esc (creates images of each event).
Run "make scenario_creator" then "./epsilon_scenario_creator.elf > scenario.esc" to create a simulator executable where events are logged to scenario.esc.

[build/makefiles] Commands to create a scenario logger and creator

---

build/targets.device.mak

The previous command added a \n at the end of the padding

[build/padding] Pad with 11 11 11 11 in hex

---

apps/shared/expression_model.cpp

The memoized expression should be reduced.

[apps] Shared: revert change on ExpressionModel

---

poincare/src/power.cpp

Fix bug: if we define f(x) = x^3-x-6, f(2) was not equal to 0 in the
values table

[poincare] Fix Power::compute precision on real numbers

---

apps/code/console_controller.cpp
apps/code/console_controller.h
apps/code/menu_controller.cpp

Scenario:
Write a script that prints "abc"
Open the console -> prints "abc"
Modify the script to print "ab"
Go back to the console -> "ab" not printed !

[apps/code] Fix console reloading that did not occur often enough

---

poincare/src/arc_cosine.cpp
poincare/src/arc_sine.cpp
poincare/src/arc_tangent.cpp
poincare/test/trigo.cpp

acos, asin: [-1,1] --> R
atan: R --> R

[poincare] Fix precision of approximation of arc trigonometry

---

poincare/src/integer.cpp

Take into accound the sign even if the approximation is infinite

[poincare] Fix Integer approximation

---

apps/shared/storage_expression_model.cpp
poincare/Makefile
poincare/include/poincare/derivative.h
poincare/include/poincare/expression.h
poincare/include/poincare/expression_node.h
poincare/include/poincare/integral.h
poincare/include/poincare/parametered_expression_helper.h
poincare/include/poincare/product.h
poincare/include/poincare/sum.h
poincare/include/poincare/symbol.h
poincare/src/derivative.cpp
poincare/src/expression.cpp
poincare/src/expression_node.cpp
poincare/src/integral.cpp
poincare/src/parametered_expression_helper.cpp
poincare/src/product.cpp
poincare/src/sum.cpp
poincare/src/symbol.cpp

In the Graph app, define f(x) = cos(x) and g(x)=diff(f(x),x,x).
The graph and table are perfectly computed, but in the Calculation apps,
g(5) fails.

[poincare] Fix the replacement of unknowns in the storage

---

apps/calculation/calculation.cpp

For instance ln(-2) in real mode should display "unreal"

[apps/calculation] Fix display of unreal

---

ion/include/ion/events.h
ion/src/simulator/init.cpp
ion/src/simulator/keyboard/fltkkbd.cpp
ion/src/simulator/keyboard/fltkkbd.h

On the simulator platform, more keyboard events are now handled (typing letters and other symbols).

Simulator cleaning

---

build/device/gdb_script.gdb
ion/src/device/keyboard.cpp
ion/src/device/keyboard.h

- Keyboard: fix an issue with the range of the output GPIO used
- Remove duplicate line in the gdb script used for the device

Fix device

---

ion/src/device/events_keyboard_platform.cpp

[ion/device] Fix unresponsive keyboard

---

ion/src/shared/unicode/utf8_helper.cpp
ion/test/utf8_helper.cpp

There was a problem with the stopping condition

[ion/utf8_helper] Fix StringGlyphLength

---

escher/src/layout_field.cpp

Otherwise it breaks the scenario:
Initial layout:   '0
"abs(x)" pressed in the toolbox => |•| is added, • being an empty layout
Final layout: |0'|

[escher/layout_field] Compute the pointed layout after the insertion

---

apps/regression/graph_controller.cpp
apps/shared/Makefile
apps/shared/text_helpers.cpp
apps/shared/text_helpers.h
apps/statistics/histogram_controller.cpp

Fix banner display

---

apps/Makefile

EPSILON_APPS_NAMES needed when building emscripten

[apps/Makefile] Fix compilation flags for apps/main.cpp

---

build/toolchain.emscripten.mak

To match the upstream change in emscripten

[emscripten] Use UTF8ToString instead of Pointer_stringify

---

poincare/src/power.cpp

Power::shallowReduce: (a^b)^c should not be applied in Real mode with (x^(1/2))^2.

[poincare] Fix power reducing

---

apps/graph/list/list_parameter_controller.cpp
escher/include/escher/table_cell.h

Function definition domain

---

apps/graph/graph/graph_controller_helper.cpp
apps/graph/graph/intersection_graph_controller.cpp
apps/graph/graph/tangent_graph_controller.cpp
apps/shared/function_banner_delegate.cpp
ion/include/ion/unicode/code_point.h

"Almost equal to" sign in banner views

---

apps/probability/distribution_curve_view.cpp

Reverts 01d2db1342666c21b2db0456a2c8ae095e6d9eb8

[apps/proba] Fix Normal distribution undercurve colouring

---

apps/shared/editable_cell_table_view_controller.h
apps/shared/values_controller.h

This fix is not great and will be improved in future commits

[apps/shared] Temporary fix: enable to display large float(-1.234567E-123) in the values controller

---

apps/graph/graph/graph_controller_helper.cpp
apps/graph/graph/intersection_graph_controller.cpp
apps/graph/graph/tangent_graph_controller.cpp
apps/shared/function_banner_delegate.cpp
ion/include/ion/unicode/code_point.h

Finally, that quick fix is not satisfactory.

Revert ""Almost equal to" sign in banner views"

---

apps/shared/expression_model.cpp
poincare/include/poincare/expression.h
poincare/include/poincare/expression_node.h
poincare/include/poincare/parametered_expression.h
poincare/include/poincare/symbol.h
poincare/src/expression.cpp
poincare/src/expression_node.cpp
poincare/src/parametered_expression.cpp
poincare/src/symbol.cpp

Use replaceSymbolWithExpression instead.

Remove Poincare::Expression::replaceUnknown

---

poincare/include/poincare/normal_distribution.h
poincare/src/inv_norm.cpp
poincare/src/norm_cdf.cpp
poincare/src/norm_cdf2.cpp
poincare/src/norm_pdf.cpp
poincare/src/normal_distribution.cpp
poincare/src/normal_distribution_function.cpp
poincare/test/approximation.cpp

In Calculation, normal distribution functions use var
In Probability, normal distribution functions uses sigma

[poincare/normal_distribution] Uses sigma, not var

---

poincare/test/expression_serialization.cpp

This should fix the CI on Windows

[poincare] Avoid rounding error

---

apps/graph/graph/graph_controller.cpp
apps/regression/graph_controller.cpp

Scenario:
f(x)=cos(x)
CalculateZeroes -> drawing glitch
Right, Back -> drawing glitch

[apps/regression/graph] Fix roundCursorView drawing glitch

---

apps/code/app.cpp
apps/code/app.h
apps/main.cpp
build/toolchain.arm-gcc-m4f.mak
build/toolchain.arm-gcc-m7f.mak
escher/include/escher/app.h
ion/include/ion.h
ion/src/device/n0100/drivers/board.cpp
ion/src/shared/console_display.cpp
ion/src/simulator/shared/main_headless.cpp
ion/src/simulator/shared/main_sdl.cpp
quiz/src/runner.cpp

Remove misc warnings on different platforms

Remove warnings

---

.github/workflows/ci-workflow.yml

Fix the CI by explicitly using the fastcomp emscripten compiler

[ci] Use fastcomp as an emscripten compiler

---

poincare/src/complex.cpp
poincare/src/complex_cartesian.cpp
poincare/src/n_ary_expression.cpp
poincare/src/trigonometry.cpp
poincare/test/simplification.cpp

- Fix sin(atan(3/4)) reduction
- Fix atan(2) reduction in Polar complex format

Poincare improvements

---

apps/graph/values/values_controller.cpp
apps/shared/values_controller.cpp

Fix graph values controller

---

ion/src/simulator/shared/events_stdin.cpp
ion/src/simulator/shared/main_headless.cpp

Fix the test target on simulator for DEBUG = 1

Fix debug test

---

apps/regression/model/model.cpp
apps/shared/expression_model.cpp
apps/shared/poincare_helpers.h
apps/solver/equation_store.cpp
apps/solver/test/equation_store.cpp
poincare/include/poincare/expression.h
poincare/include/poincare/expression_node.h
poincare/include/poincare/multiplication.h
poincare/include/poincare/power.h
poincare/include/poincare/rational.h
poincare/src/addition.cpp
poincare/src/equal.cpp
poincare/src/expression.cpp
poincare/src/expression_node.cpp
poincare/src/matrix.cpp
poincare/src/multiplication.cpp
poincare/src/power.cpp
poincare/src/rational.cpp
poincare/test/expression_properties.cpp
poincare/test/helper.cpp
poincare/test/helper.h
poincare/test/simplification.cpp

[poincare] Power: when reducing, apply multinome development only when the target is the User

---

escher/include/escher/responder.h
escher/src/responder.cpp

Some cleaning of the responder class

Responder common ancestor

---

ion/src/device/bench/Makefile
ion/src/device/bench/bench.cpp
ion/src/device/bench/command/command.h
ion/src/device/bench/command/usb_plugged.cpp

This commit is in the branch version-11-n0110, we cherry-pick it in master

[bench] USBPlugged command

---

apps/code/console_controller.cpp
apps/code/console_edit_cell.cpp
apps/code/console_edit_cell.h
escher/include/escher/text_field.h

[apps/code] Fix input(), that did not return the input

---

apps/code/console_controller.cpp

Fixes #1316 
```
while (True):
print("hello")
```
is now interruptible when the user presses Back

[apps/code] Allow interruption of infinite print loops

---

python/port/port.cpp

print can be user interrupted, so the interruption char needs to be
set for the whole runCode method

[python/port] Fix user interruption char set up

---

apps/calculation/additional_outputs/expressions_list_controller.cpp
apps/calculation/additional_outputs/illustrated_list_controller.cpp

Scenario: Open several times the additional outputs menu, there are
drawing problems (multiple stack headers)

[apps/calc] Do not forget to call parent method

---

ion/src/simulator/web/simulator.html

The screenshot and fullscreen buttons hid the last row of the calculator

Fix web simulator buttons position

---

poincare/include/poincare/tree_handle.h
poincare/include/poincare/tree_node.h
poincare/include/poincare/tree_pool.h
poincare/src/tree_pool.cpp

Unsigned types are never negative.

[poincare] Fix checking for special tree identifier value

---

apps/code/console_edit_cell.cpp

[apps/console_edit_cell] Fix input result copying

---

poincare/src/absolute_value.cpp

This fixes abs(-2.3*10^-39) that returned a negative value

[poincare/absolute_value] ShallowReduce done in double, not float

---

apps/calculation/additional_outputs/complex_graph_cell.cpp
apps/calculation/additional_outputs/complex_graph_cell.h
apps/calculation/additional_outputs/trigonometry_graph_cell.h
apps/regression/graph_view.cpp
apps/regression/graph_view.h
apps/shared/Makefile
apps/shared/curve_view.h
apps/shared/function_graph_view.cpp
apps/shared/function_graph_view.h
apps/shared/labeled_curve_view.cpp
apps/shared/labeled_curve_view.h
apps/statistics/box_axis_view.cpp
apps/statistics/box_axis_view.h
apps/statistics/box_view.h
apps/statistics/histogram_view.cpp
apps/statistics/histogram_view.h

There was a lot of code duplication.
I removed the initialization of xLabel{} and yLabels{} because those are
scratch buffers that shouldn't be accessed before being written to
anyway.

[apps/shared] Factorize CurveView::label

---

apps/graph/app.cpp
apps/graph/graph/graph_controller.cpp
apps/graph/graph/graph_controller.h
apps/regression/app.cpp
apps/regression/app.h
apps/regression/graph_controller.cpp
apps/regression/graph_controller.h
apps/regression/store.cpp
apps/regression/store.h
apps/sequence/app.cpp
apps/sequence/graph/graph_controller.cpp
apps/sequence/graph/graph_controller.h
apps/shared/function_app.cpp
apps/shared/function_app.h
apps/shared/function_graph_controller.cpp
apps/shared/function_graph_controller.h
apps/shared/function_store.cpp
apps/shared/function_store.h
apps/shared/interactive_curve_view_controller.cpp
apps/shared/interactive_curve_view_controller.h

Scenario:
f(t) = [t^2  t+1] in parametric
Display the graph
f(x) = 1 on ]-inf;0]
g(x) = 2 on [0;inf[
Display the graph -> the range did not change

Fix ranges reloading

---

poincare/include/poincare/approximation_helper.h
poincare/include/poincare/power.h
poincare/include/poincare/trigonometry.h
poincare/src/approximation_helper.cpp
poincare/src/arc_cosine.cpp
poincare/src/arc_sine.cpp
poincare/src/arc_tangent.cpp
poincare/src/cosine.cpp
poincare/src/hyperbolic_arc_cosine.cpp
poincare/src/hyperbolic_arc_sine.cpp
poincare/src/hyperbolic_arc_tangent.cpp
poincare/src/hyperbolic_cosine.cpp
poincare/src/hyperbolic_sine.cpp
poincare/src/hyperbolic_tangent.cpp
poincare/src/nth_root.cpp
poincare/src/power.cpp
poincare/src/sine.cpp
poincare/src/square_root.cpp
poincare/src/tangent.cpp
poincare/src/trigonometry.cpp
poincare/test/approximation.cpp
poincare/test/helper.cpp
poincare/test/helper.h
poincare/test/simplification.cpp

- Fix wrong power approximation: (-10)^0.00000001 ~ 1 instead of ~1+3.141593ᴇ-8*i
- Fix precision loss in power approximation
See issue #1350 for more details

Poincare fix precision errors

---

poincare/include/poincare/power.h
poincare/src/nth_root.cpp
poincare/src/power.cpp

PowerNode::tryComputeRealRootOfRationalPow --> PowerNode::computeNotPrincipalRealRootOfRationalPow

Clean name in Poincare::Power

---

apps/probability/distribution/distribution.cpp
apps/probability/test/distributions.cpp

Fix probability law finite integral

---

ion/src/simulator/android/src/java/com/numworks/calculator/EpsilonActivity.java

This is a hack, we should find why this was broken after v12.

[ion/android] Hide the status bar and navigation buttons

---

poincare/include/poincare/approximation_helper.h
poincare/src/approximation_helper.cpp
poincare/src/expression.cpp
poincare/src/power.cpp
poincare/test/simplification.cpp

- Avoid infinite loop : a^x*b^x --> (a¨b)^x --> a^x*b^x --> (a^b)^x when a and b are very big integers
- Avoid approximating 1.0E+92^(-0.5) --> 0.0

Fix poincare crash

---

build/all.mak
build/targets.mak

- Use a standalone makefile
- Fix short Android/iOS recipes

Fix all official

---

apps/empty_battery_window.cpp
apps/global_preferences.h
apps/i18n.py
apps/settings/main_controller.cpp
apps/shared/language_controller.cpp
escher/include/escher/i18n.h
quiz/src/i18n.cpp

This PR fixes the problem that was spotted by #569

Fix default language

---

apps/code/script_store.cpp

This patch #346
Note : this is a reopen of https://github.com/numworks/epsilon/pull/1402

Don't scan not loaded script in toolbox

---

apps/global_preferences.h

This is a duplicate of #936, to rebase the PR before merging it

Increase Brightness Levels to 12

---

escher/src/layout_field.cpp
escher/src/run_loop.cpp
ion/include/ion/events.h
poincare/include/poincare/layout_cursor.h

Avoid a bunch of switch cases by using simple arithmetic

[LayoutField] Clean direction handling

---

.github/workflows/ci-workflow.yml
poincare/src/unit.cpp
poincare/test/approximation.cpp
poincare/test/simplification.cpp

- make sure that a test failure is detected by the CI on windows platform
- fix some tests on windows

CI windows

---

.github/workflows/metrics-workflow.yml
build/metrics/binary_size.py

Note that .text and .rodata are cumulative (internal+external).

[ci] Report the size of .text, .rodata, .bss and .data sections

---

apps/shared/interval.cpp
apps/shared/interval.h
apps/shared/interval_parameter_controller.cpp

This fixes https://github.com/numworks/epsilon/issues/666

[Interval] Patch the need recomputing

---

poincare/include/poincare/normal_distribution.h

We limited the precision too much before.

[poincare/normal_distribution] More values are computed

---

apps/shared/zoom_parameter_controller.cpp

This fixes #500
And I can't find any consequences of this switch.

[App/zoom_parameter_controller] Changed subview order

---

apps/calculation/additional_outputs/illustrated_list_controller.cpp
apps/calculation/additional_outputs/scrollable_three_expressions_cell.cpp
apps/calculation/additional_outputs/scrollable_three_expressions_cell.h
apps/calculation/calculation.cpp
apps/calculation/calculation.h
apps/calculation/history_controller.cpp
apps/calculation/history_controller.h
apps/calculation/history_view_cell.cpp
apps/calculation/history_view_cell.h
apps/shared/scrollable_multiple_expressions_view.cpp
apps/shared/scrollable_multiple_expressions_view.h
escher/include/escher/metric.h
escher/src/scroll_view.cpp
kandinsky/src/rect.cpp

Fixes #935 
This is a rebase of #1345 + it fixes some alignment and margin issues / calculation height computation / history navigation handling.
Based on #954 and Omega-Numworks#238

Rebase of 0b101's epsilon compact result

---

apps/calculation/additional_outputs/scrollable_three_expressions_cell.cpp

[apps/calculation] Fix height computation in additional results

---

ion/src/simulator/shared/events_keyboard.cpp
ion/src/simulator/shared/main_sdl.cpp

This fixes #1575 and probably #1300 too.

Fix simulator relayout

---

poincare/src/power.cpp
poincare/test/helper.cpp
poincare/test/helper.h
poincare/test/simplification.cpp

Scenario: f(x) = 0->0
In graph, go to x = e^(f(0))

[poincare/power] Fix shallowReduce

---

apps/graph/graph/preimage_parameter_controller.cpp
apps/graph/graph/preimage_parameter_controller.h
apps/regression/go_to_parameter_controller.cpp
apps/regression/go_to_parameter_controller.h
apps/shared/function_go_to_parameter_controller.cpp
apps/shared/function_go_to_parameter_controller.h
apps/shared/go_to_parameter_controller.cpp
apps/shared/go_to_parameter_controller.h
apps/shared/interactive_curve_view_controller.cpp
apps/shared/interactive_curve_view_controller.h
apps/shared/interval.cpp
apps/shared/interval.h
apps/shared/interval_parameter_controller.cpp
apps/shared/interval_parameter_controller.h
apps/shared/range_parameter_controller.cpp
apps/shared/range_parameter_controller.h

Rebase of https://github.com/numworks/epsilon/pull/1563

[Apps/Shared] Fixed interval and curve view exit

---

apps/calculation/calculation.cpp
poincare/src/expression.cpp
poincare/src/multiplication.cpp

Fixes the following scenario, which crashed on simulator with debug = 1.
Enter "[5000000000000000]^20 _s" in the calculation app

Fix Calculation::additionalInformationType

---

apps/calculation/history_view_cell.cpp
apps/shared/scrollable_multiple_expressions_view.cpp
apps/shared/scrollable_multiple_expressions_view.h

[apps/shared] Handle identical layout in MinimalSizeForOptimalDisplay

---

python/port/port.cpp

This PR adds magenta color to MicroPython

[python] Add magenta color

---

apps/graph/graph/graph_view.cpp
apps/shared/curve_view.cpp
apps/shared/curve_view.h

Do not draw vertical asymptotes

---

.github/workflows/ci-workflow.yml
ion/src/simulator/shared/main_headless.cpp

This PR fixes the CI for Windows and MacOS

CI fix for Windows and MacOS

---

python/port/mpconfigport.h

This fixes https://github.com/numworks/epsilon/issues/1709

[py] Support round on int

---

.github/workflows/metrics-workflow.yml

This reverts commit 110f33312264861427280414798d8170a4468488.

Revert "[github/workflows] Update Metrics to remove NumWorksBot"

---

build/targets.simulator.windows.mak

This fixes https://github.com/numworks/epsilon/issues/1778

[makefiles] Fix epsilon_run on windows

---

build/device/dfu.py
build/device/usb/__init__.py
build/device/usb/_debug.py
build/device/usb/_interop.py
build/device/usb/_lookup.py
build/device/usb/_objfinalizer.py
build/device/usb/backend/__init__.py
build/device/usb/backend/libusb0.py
build/device/usb/backend/libusb1.py
build/device/usb/backend/openusb.py
build/device/usb/control.py
build/device/usb/core.py
build/device/usb/legacy.py
build/device/usb/libloader.py
build/device/usb/util.py

This fixes https://github.com/numworks/epsilon/issues/1742

[pyUSB] Update and fix on python 3.9

---

apps/math_variable_box_controller.cpp

This fixes https://github.com/numworks/epsilon/issues/1760

[Variable box] Do not replace symbol in sequence name
